MODULES+=	upstream-jdomain

MODULE_SUMMARY_upstream_jdomain=	3rd-party upstream jdomain module

include $(CONTRIB)/src/ngx_http_upstream_jdomain_module/version

MODULE_VERSION_upstream_jdomain=	$(UPSTREAM_JDOMAIN_NGINX_MODULE_VERSION)
MODULE_RELEASE_upstream_jdomain=	1

MODULE_VERSION_PREFIX_upstream_jdomain=$(MODULE_TARGET_PREFIX)

MODULE_SOURCES_upstream_jdomain=	ngx_http_upstream_jdomain_module-$(UPSTREAM_JDOMAIN_NGINX_MODULE_GITHASH).tar.xz

MODULE_CONFARGS_upstream_jdomain=	--add-dynamic-module=$(MODSRC_PREFIX)ngx_http_upstream_jdomain_module-$(UPSTREAM_JDOMAIN_NGINX_MODULE_GITHASH)

.deps-module-upstream-jdomain:
	cd $(CONTRIB) && make .sum-ngx_http_upstream_jdomain_module
	touch $@

prerequisites-for-module-upstream-jdomain:

define MODULE_POST_upstream_jdomain
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_upstream_jdomain) for $(MODULE_SUMMARY_PREFIX) has been installed.
To enable this module, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_http_upstream_jdomain_module.so;

Please refer to the module documentation for further details:
https://github.com/nicholaschiasson/ngx_upstream_jdomain

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_upstream_jdomain
